//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetalleSimulacion
    {
        public int Id { get; set; }
        public string Cedula { get; set; }
        public double Porcentaje { get; set; }
        public double Impuesto { get; set; }
        public double Patrimonio { get; set; }
        public int Id_Simulacion { get; set; }
    
        public virtual Simulacion Simulacion { get; set; }
    }
}
