//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAppCurso.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Simulacion
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Simulacion()
        {
            this.DetalleSimulacions = new HashSet<DetalleSimulacion>();
        }
    
        public int Id { get; set; }
        public string Usuario { get; set; }
        public string CedulaSolicitante { get; set; }
        public string NombreSolicitante { get; set; }
        public double PatrimonioFamiliar { get; set; }
        public int Herederos { get; set; }
        public double Impuesto { get; set; }
        public double PatrimonioHeredar { get; set; }
        public System.DateTime Fecha { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DetalleSimulacion> DetalleSimulacions { get; set; }
    }
}
